### ISSUE TITLE
Need a bit more explanation of how to program Rev C boards

### ISSUE THREAD

**Issue by ultimav** [sonocotta/attiny1616-dev-board#3]
I followed the guide for A/B Revisions, up to a point as there is only a mention of the C board saying that everything is just Plug/Play

Using Ardiuno 1.8.13 on MacOS
Downloaded megaTinyCode from Spencers Konde repo (since the URL is broken because of SSL), and put it in the hardware folder.
I have matched up all the settings.
I also followed the Spencers instructions to download the Python3 portable in the ~/megaTinyCore/megaavr/tools/ folder and unpack it.

My code 'compiles' for the 1616, but i can't figure out what i am doing wrong to upload. Since this is Rev C, I assume I can use a USB cable to connect directly from the dev board to my mac,(and it appears as a Serial port.) Both upload and Upload with Programmer fail with the same error.

That the Serial device Resource is busy.

**Comment by anabolyc** [comment]
Hey Dana. Sorry for the late reply, I’m out of office this week. Looks like
you’re on the right track, pls double check if the right port selected in
arduino settings and no other app uses this port, serial monitor for
example. Please also check with other Arduino boards if you able to flash
to exclude port permissions issues. If nothog helps add arduino logs here,
i’ll try to reproduce

**Comment by ultimav** [comment]
Omg. In my haste to figure out the right combo of IDE version and libraries I did have 2 versions running fighting over the port.

Onve i got the other shutdown everything worked and I successfully flashed it. Sorry for the false alarm.
